services:
  book-env:
    image: cchang5/dsci_522_group_8_bank_marketing:58fe205
    ports:
      - "8889:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
      
