# Reference: UBC MDS DSCI_573
# conda env create -f environment.yaml

name: 'bank_marketing_analysis'
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - python=3.10
    - ipykernel=6.26.0
    - matplotlib>=3.8.0
    - pandas>=2.1.1
    - scikit-learn>=1.3.1    
    - requests>=2.24.0
    - ipython
    - graphviz
    - python-graphviz
    - lightgbm
    - altair=5.1.2
    - altair_viewer
    - vl-convert-python  
    - vegafusion=1.4.3  
    - vegafusion-python-embed  
    - vegafusion-jupyter=1.4.3  
    - vega_datasets     
    - jinja2
    - pip>=23.2.1    
    - pip:
        - mglearn
        - graphviz
        - psutil>=5.7.2
        - ucimlrepo
